server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ai_study_planner_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-v1: ${JWT_SECRET_V1:6KkpGcRg8HpHdJksM7HLbA8ZOYfhED7EPv4oVNLrPwM=}
  generate-key: false   # change true to generate key
  debug: false          # debug mode
  access:
    expiration: 1800000
  refresh:
    expiration: 604800000

openRouter:
  custom-api-key: ${OPENROUTER_API_KEY}
  model: nvidia/nemotron-3-super-120b-a12b:free
#  model: openai/gpt-oss-20b:free
  url: https://openrouter.ai/api/v1/chat/completions

storage:
  s3:
    bucket: ${S3_BUCKET:eventhub-media-tnhieu-2026}
    access-key: ${S3_ACCESS_KEY:''}
    secret-key: ${S3_SECRET_KEY:''}
    region: ${S3_REGION:ap-southeast-2}
    public-base-url: ${S3_PUBLIC_BASE_URL:https://eventhub-media-tnhieu-2026.s3.ap-southeast-2.amazonaws.com}