name: Deploy Backend to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: chmod +x mvnw && ./mvnw clean package -DskipTests

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/app/"

      - name: Deploy & Run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/app

            echo "Creating .env file..."
            cat > .env <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            echo "Export environment variables..."
            export $(grep -v '^#' .env | xargs)

            echo "Stopping old app..."
            pkill java || true

            echo "Starting new app..."
            nohup java -jar *.jar > app.log 2>&1 &
